name: Release Assets

on:
  workflow_dispatch:

jobs:
  PulishAssets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15'

      - uses: healthplace/npmrc-registry-login-action@v1.0
        with:
          scope: ''
          registry: 'https://registry.npmjs.org/'
          auth-token: ${{ secrets.NPM_TOKEN }}

      - name: unpublish package
        run: |
          cd source/assets
          npm unpublish dd_blog_assets@2.0.0

      - name: publish npm package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./source/assets

  BuildAssets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build project 
        run: |
          cd source/assets && zip -r dd_blog_assets.zip *
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #   with:
      #     tag_name: 1.0.0
      #     release_name: dd_blog_assets
      #     body: |
      #       # Release Notes
      #       dd_blog_assets
      #     draft: false
      #     prerelease: false
      # - name: Upload Release Assets
      #   id: upload_release_assets
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./dd_blog_assets.zip
      #     asset_name: dd_blog_assets
      #     asset_content_type: application/octet-stream
      - name: Upload Release Assets
        id: upload_release_assets
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          name: dd_blog_assets
          tag: 1.0.0
          artifacts: "source/assets/dd_blog_assets.zip"
          allowUpdates: true
          replacesArtifacts: true
          body: dd_blog_assets